[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "lae"
version = "0.1.0"
description = "Custom BERT implementation with Flash Attention and Triton components"
readme = "README.md"
requires-python = ">=3.11,<3.12"
license = {text = "MIT"}
authors = [
  {name = "Ryan Synk", email = "ryansynk@umd.edu"}
]

dependencies = [
    "torch>=2.6",
    "transformers<=4.57.1",
    "einops",
    "altair",
    "biopython",
    "edlib",
    "jsonargparse",
    "numpy",
    "polars",
    "pyarrow",
    "sourmash",
    "tqdm",
    "wandb",
    "pyyaml",
    "zstandard",
    "flash-attn==2.7.4.post1+cu12torch2.6cxx11abiFALSE",
    "ipython>=9.10.0",
    "ipdb>=0.13.13",
    "pyfaidx>=0.9.0.3",
    "vl-convert-python>=1.9.0.post1",
    "metagraph-api",
    "evo2>=0.5.5",
    "setuptools>=82.0.1",
    "streamlit>=1.56.0",
    "diskannpy>=0.7.0",
    "scikit-learn>=1.8.0",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "black",
    "ruff",
    "ipython"
]

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu124"
explicit = true

[tool.uv.sources]
metagraph-api = { git = "https://github.com/ratschlab/metagraph.git", subdirectory = "metagraph/api/python" }
torch = { index = "pytorch"}
flash-attn = { url = "https://github.com/Dao-AILab/flash-attention/releases/download/v2.7.4.post1/flash_attn-2.7.4.post1+cu12torch2.6cxx11abiFALSE-cp311-cp311-linux_x86_64.whl" }
# CRITICAL for your directory structure
# This explicitly tells setuptools to look for the 'locale' directory
[tool.setuptools.packages.find]
include = ["lae*"]
exclude = ["training*", "tests*"]
