unsupervised: false
num_epochs: 1
dataset_path: /fs/nexus-scratch/ryansynk/rawbert_data/data/train_contigs.parquet
val_dataset_path: /fs/nexus-scratch/ryansynk/rawbert_data/data/val_contigs.parquet
batch_size: 256
val_batch_size: 512
schedule: hold
lr: 0.001
backbone_lr: 4.0e-06
total_samples: 258_560
warmup_fraction: null
warmup_samples: 76_800
moco_queue_size: 65536
moco_momentum: 0.999
moco_softmax_temp: 0.07
checkpoint_dir: /fs/nexus-scratch/ryansynk/rawbert/checkpoints/
checkpoint_interval_samples: 256_000
num_val_queries: 100
num_val_keys: 10000
dim: 128
pooling: mean
sanity_test: false
augment_config:
  max_len: 1024
  min_seq_len: 150
  containment_prob: 0.66
  overlap_prob: 0.34
  min_alignment_len: 149
  max_alignment_ratio: 1.0
  min_coverage: 0.1
  insertion_rate: 0.005
  deletion_rate: 0.005
  substitution_rate: 0.02
  average_insertion_length: 10
  average_deletion_length: 10
  substitution_matrix:
    A:
    - 0.0
    - 0.15
    - 0.77
    - 0.08
    C:
    - 0.13
    - 0.0
    - 0.17
    - 0.7
    G:
    - 0.7
    - 0.17
    - 0.0
    - 0.13
    T:
    - 0.08
    - 0.78
    - 0.14
    - 0.0
