unsupervised: true
data_type: reference 
num_epochs: 1
dataset_path: /pscratch/sd/r/rsynk/reference_data/ncbi_dataset/data
val_dataset_path: ""
batch_size: 32
val_batch_size: 32
schedule: cosine
lr: 0.000353
backbone_lr: 0.00001061
total_steps: 8000
warmup_fraction: 0.08
warmup_steps: null
moco_queue_size: 8192
moco_momentum: 0.99
moco_softmax_temp: 0.07
moco_filter_queue: True 
moco_filter_queue_identity_cutoff: 0.91
checkpoint_dir: /pscratch/sd/r/rsynk/rawbert/checkpoints/
checkpoint_interval: 1000
num_val_queries: 64
num_val_keys: 8192
dim: 128
pooling: max
num_workers: 4
sanity_test: false
augment_config:
  max_len: 1024
  max_seq_len: 1024
  min_seq_len: 31
  min_overlap_percent: 0.4
  containment_prob: 1.0
  overlap_prob: 0.0
  min_alignment_len: 149
  max_alignment_ratio: 1.0
  min_coverage: 0.1
  alignment_threshold: 0.6
  max_containment_ratio: 1.0
  min_read_len: 91
  max_read_len: 150
  identity_mean: 95
  identity_max: 99
  identity_stdev: 2.5
  disable_mutations: True 
  insertion_rate: 0.005
  deletion_rate: 0.005
  substitution_rate: 0.02
  average_insertion_length: 10
  average_deletion_length: 10
  substitution_matrix:
    A:
    - 0.0
    - 0.15
    - 0.77
    - 0.08
    C:
    - 0.13
    - 0.0
    - 0.17
    - 0.7
    G:
    - 0.7
    - 0.17
    - 0.0
    - 0.13
    T:
    - 0.08
    - 0.78
    - 0.14
    - 0.0
