unsupervised: true
num_epochs: 1
dataset_path: /pscratch/sd/r/rsynk/data/train/logan_contig/all_contigs.parquet
val_dataset_path: /pscratch/sd/r/rsynk/data/val/logan_contig/all_contigs.parquet
per_device_batch_size: 64
val_batch_size: 512
schedule: cosine
lr: 0.001
backbone_lr: 0.00006
total_steps: 8000
warmup_fraction: 0.08
warmup_steps: null
moco_queue_size: 131072
moco_momentum: 0.9995
moco_softmax_temp: 0.05
moco_filter_queue: True 
moco_filter_queue_identity_cutoff: 0.91
checkpoint_dir: /pscratch/sd/r/rsynk/rawbert/checkpoints/
checkpoint_interval: 1000
num_val_queries: 100
num_val_keys: 10000
dim: 128
pooling: mean
num_workers: 24
sanity_test: false
use_projection_head: False
augment_config:
  max_len: 256
  max_seq_len: 256
  min_seq_len: 31
  min_overlap_percent: 0.4
  containment_prob: 1.0
  overlap_prob: 0.0
  alignment_threshold: 0.6
  identity_mean: 95
  identity_max: 99
  identity_stdev: 2.5
  disable_mutations: False
  insertion_rate: 0.005
  deletion_rate: 0.005
  substitution_rate: 0.02
  average_insertion_length: 10
  average_deletion_length: 10
  substitution_matrix:
    A:
    - 0.0
    - 0.15
    - 0.77
    - 0.08
    C:
    - 0.13
    - 0.0
    - 0.17
    - 0.7
    G:
    - 0.7
    - 0.17
    - 0.0
    - 0.13
    T:
    - 0.08
    - 0.78
    - 0.14
    - 0.0
